### ISSUE TITLE
Retro Pixel Max producing Black screen on Unity 5.4.1f1

### ISSUE THREAD

**Issue by hcorion** [oxysoft/RetroSuite3D#1]
I have no idea what the problem is, but it is not working. All the other scripts work, just not Retro Pixel Max. I'm using the example scene, and haven't changed anything. Of course I had to update because it was built for unity version 5.3.5.
Specs: 
Windows 10 64-bit
NVIDIA GTX 1070 with latest drivers
intel i7 4770

**Comment by oxysoft** [comment]
If the demo scene is rendering a black screen and you didn't modify anything, I'm not sure what to tell you. Hopefully it's not weird platform specific shit.

**Comment by hcorion** [comment]
Have you tried it on Unity v5.4.1? does it work on your computer?

**Comment by oxysoft** [comment]
I'm using 5.3.5f1 and it does work fine for me. I'll try updating to 5.4.1 soon and see what happens

**Comment by alex-carlson** [comment]
I've also got this problem on 5.4.0f3, upgraded to 5.4.1f1 and it's still happening.  Tweaking the shader in your demo, I can get a black/white separation if I change dist to 0.5 is the pixel max shader code.

I'm running macOS El Capitan as well.

**Comment by oxysoft** [comment]
Give me a bit, I'm going to upgrade and try to see what's up

**Comment by oxysoft** [comment]
Okay so it does seem like the palette image effects break in the new version, I'm gonna try to find the issue

**Comment by oxysoft** [comment]
Found it, we have to send the palette to the shader differently. I've committed the changes
